version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 294951093594.dkr.ecr.ap-northeast-2.amazonaws.com/frontend
      
      # [추가] Secrets Manager에서 JSON 데이터를 가져와 .env.production 파일 생성
      # 'prod/frontend-secrets' 부분은 실제 본인의 시크릿 이름으로 수정하세요.
      - echo "Retrieving secrets from Secrets Manager (about/frontend)..."
      - aws secretsmanager get-secret-value --secret-id about/frontend --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env.production
      - echo ".env.production file created successfully"

  build:
    commands:
      - echo Building Docker image...
      # .env.production 파일이 빌드 컨텍스트에 포함되므로 별도의 --build-arg는 필요 없습니다.
      - docker build -t next-app .
      - docker tag next-app 294951093594.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 294951093594.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**