# builder
FROM public.ecr.aws/docker/library/node:20.11.0 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install -g npm@10.2.4 && npm install
COPY . .

# ✅ 여기에 CookiePay 포함해서 ARG 선언 전부
ARG NEXT_PUBLIC_SERVER_URI
ARG NEXT_PUBLIC_NEXTAUTH_URL
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_KAKAO_CLIENT_ID
ARG NEXT_PUBLIC_KAKAO_JS
ARG NEXT_PUBLIC_KAKAO_JS_KEY
ARG NEXT_PUBLIC_PWA_KEY
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_NAVER_CLIENT_SECRET
ARG NEXT_PUBLIC_NAVER_CLIENT_ID
ARG NEXT_PUBLIC_NAVER_AI_CLIENT_ID
ARG NEXT_PUBLIC_TOSS_CLIENT_KEY
ARG NEXT_PUBLIC_COOKIEPAY_API_ID

# ✅ 서버 전용(비공개)도 빌드에서 필요하면 ARG로(보통은 필요 없음)
ARG COOKIEPAY_API_ID
ARG COOKIEPAY_API_KEY
ARG COOKIEPAY_MODE
ARG COOKIEPAY_BASE_URL
ARG NEXTAUTH_SECRET

# ✅ Next build에 NEXT_PUBLIC_*는 반드시 들어가야 함
ENV NEXT_PUBLIC_SERVER_URI=$NEXT_PUBLIC_SERVER_URI \
    NEXTAUTH_URL=$NEXTAUTH_URL \
    NEXT_PUBLIC_NEXTAUTH_URL=$NEXT_PUBLIC_NEXTAUTH_URL \
    NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
    NEXT_PUBLIC_KAKAO_CLIENT_ID=$NEXT_PUBLIC_KAKAO_CLIENT_ID \
    NEXT_PUBLIC_KAKAO_JS=$NEXT_PUBLIC_KAKAO_JS \
    NEXT_PUBLIC_KAKAO_JS_KEY=$NEXT_PUBLIC_KAKAO_JS_KEY \
    NEXT_PUBLIC_NAVER_CLIENT_SECRET=$NEXT_PUBLIC_NAVER_CLIENT_SECRET \
    NEXT_PUBLIC_NAVER_CLIENT_ID=$NEXT_PUBLIC_NAVER_CLIENT_ID \
    NEXT_PUBLIC_NAVER_AI_CLIENT_ID=$NEXT_PUBLIC_NAVER_AI_CLIENT_ID \
    NEXT_PUBLIC_PWA_KEY=$NEXT_PUBLIC_PWA_KEY \
    NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID \
    NEXT_PUBLIC_TOSS_CLIENT_KEY=$NEXT_PUBLIC_TOSS_CLIENT_KEY \
    NEXT_PUBLIC_COOKIEPAY_API_ID=$NEXT_PUBLIC_COOKIEPAY_API_ID


# ❗️(중요) 여기서 COOKIEPAY_API_KEY 같은 비밀키는 Next 빌드에 굳이 넣지 말자.
RUN npm run build


# production
FROM public.ecr.aws/docker/library/node:20.11.0 AS production
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

# ✅ 런타임 env는 docker run --env-file 로 들어오니까
# 여기서 굳이 ENV로 박아둘 필요 없음 (오히려 헷갈림)
EXPOSE 3000
CMD ["npm", "start"]
