import { ActiveLocation } from "../../../types/services/locationTypes";
import {
  ANYANG_금정역,
  ANYANG_범계역,
  ANYANG_범계학원가점,
  ANYANG_안양역,
  ANYANG_인덕원역,
  ANYANG_호계점,
  DONG_경희대점,
  DONG_길음역,
  DONG_동대문역,
  DONG_딥십리역,
  DONG_서울시립대점,
  DONG_석계역,
  DONG_성신여대점,
  DONG_신설동역,
  DONG_안암역,
  DONG_왕십리역,
  DONG_월곡역,
  DONG_장안동사거리점,
  DONG_혜화역,
  DONG_화랑대역,
  GANGNAM_강남역,
  GANGNAM_강남역구청역,
  GANGNAM_교대역,
  GANGNAM_논현역,
  GANGNAM_도곡동점,
  GANGNAM_선릉역,
  GANGNAM_신논현역,
  GANGNAM_양재,
  INC_구월동점,
  INC_송도점,
  INC_송도점DT점,
  INC_인하대점,
  SUWAN_경기대,
  SUWAN_경희대,
  SUWAN_고색역,
  SUWAN_광교,
  SUWAN_광교엘리웨이,
  SUWAN_광교역,
  SUWAN_구운동,
  SUWAN_망포역,
  SUWAN_상현역,
  SUWAN_성균관대역,
  SUWAN_송죽,
  SUWAN_수원시청,
  SUWAN_수원역,
  SUWAN_아주대,
  SUWAN_행궁동,
  YANG_까치산역,
  YANG_당산역,
  YANG_등촌역,
  YANG_목동점,
  YANG_발산역,
  YANG_신길역,
  YANG_신도림역,
  YANG_신월동점,
  YANG_신풍역,
  YANG_양천구청역,
  YANG_여의도역,
  YANG_영등포구청역,
  YANG_오목교역,
  YANG_화곡DT점,
  YANG_화곡역,
} from "./studyPlaceConstants";

interface ILocationPair {
  [key: number]: [string, string][];
}

//15 //25
export const STUDY_DISTANCE: {
  [key in ActiveLocation]: ILocationPair;
} = {
  수원: {
    1: [
      [SUWAN_수원시청, SUWAN_수원역],
      [SUWAN_수원시청, SUWAN_망포역],
      [SUWAN_수원시청, SUWAN_아주대],
      [SUWAN_수원시청, SUWAN_고색역],
      [SUWAN_수원역, SUWAN_고색역],
      [SUWAN_수원역, SUWAN_성균관대역],
      [SUWAN_수원역, SUWAN_행궁동],

      [SUWAN_수원역, SUWAN_구운동],
      [SUWAN_경희대, SUWAN_망포역],
      [SUWAN_아주대, SUWAN_광교역],
      [SUWAN_아주대, SUWAN_광교],
      [SUWAN_아주대, SUWAN_광교엘리웨이],
      [SUWAN_아주대, SUWAN_행궁동],
      [SUWAN_아주대, SUWAN_상현역],
      [SUWAN_광교역, SUWAN_광교],
      [SUWAN_광교역, SUWAN_행궁동],
      [SUWAN_광교역, SUWAN_상현역],
      [SUWAN_구운동, SUWAN_고색역],
      [SUWAN_구운동, SUWAN_성균관대역],
      [SUWAN_상현역, SUWAN_광교],
      [SUWAN_상현역, SUWAN_광교역],
      [SUWAN_상현역, SUWAN_광교엘리웨이],
      [SUWAN_광교엘리웨이, SUWAN_광교],
      [SUWAN_송죽, SUWAN_행궁동],
      [SUWAN_송죽, SUWAN_성균관대역],
      [SUWAN_경기대, SUWAN_광교],
      [SUWAN_경기대, SUWAN_광교역],
      [SUWAN_경기대, SUWAN_행궁동],
      [SUWAN_경기대, SUWAN_송죽],
    ],
    2: [
      [SUWAN_고색역, SUWAN_성균관대역],
      [SUWAN_고색역, SUWAN_망포역],
      [SUWAN_수원시청, SUWAN_행궁동],
      [SUWAN_수원시청, SUWAN_경희대],
      [SUWAN_수원역, SUWAN_망포역],
      [SUWAN_수원시청, SUWAN_광교엘리웨이],
      [SUWAN_수원시청, SUWAN_광교],
      [SUWAN_아주대, SUWAN_수원역],
      [SUWAN_아주대, SUWAN_송죽],
      [SUWAN_수원역, SUWAN_송죽],
      [SUWAN_성균관대역, SUWAN_행궁동],
      [SUWAN_고색역, SUWAN_행궁동],
      [SUWAN_망포역, SUWAN_광교엘리웨이],
      [SUWAN_경희대, SUWAN_광교엘리웨이],
      [SUWAN_광교엘리웨이, SUWAN_광교역],
      [SUWAN_구운동, SUWAN_행궁동],
      [SUWAN_구운동, SUWAN_수원시청],
      [SUWAN_구운동, SUWAN_송죽],
      [SUWAN_행궁동, SUWAN_광교],
      [SUWAN_상현역, SUWAN_행궁동],
    ],
  },
  안양: {
    1: [
      [ANYANG_범계역, ANYANG_범계학원가점],
      [ANYANG_범계역, ANYANG_인덕원역],
      [ANYANG_범계역, ANYANG_금정역],
      [ANYANG_범계역, ANYANG_호계점],
      [ANYANG_안양역, ANYANG_금정역],
      [ANYANG_호계점, ANYANG_금정역],
      [ANYANG_호계점, ANYANG_범계학원가점],
    ],
    2: [
      [ANYANG_범계역, ANYANG_안양역],
      [ANYANG_안양역, ANYANG_호계점],
      [ANYANG_인덕원역, ANYANG_호계점],
      [ANYANG_안양역, ANYANG_범계학원가점],
      [ANYANG_안양역, ANYANG_인덕원역],
      [ANYANG_금정역, ANYANG_범계학원가점],
      [ANYANG_금정역, ANYANG_인덕원역],
      [ANYANG_인덕원역, ANYANG_범계학원가점],
    ],
  },
  양천: {
    1: [
      [YANG_신월동점, YANG_까치산역],
      [YANG_화곡역, YANG_까치산역],
      [YANG_화곡역, YANG_화곡DT점],
      [YANG_화곡역, YANG_등촌역],
      [YANG_화곡역, YANG_신월동점],

      [YANG_까치산역, YANG_양천구청역],
      [YANG_까치산역, YANG_오목교역],
      [YANG_까치산역, YANG_화곡DT점],
      [YANG_양천구청역, YANG_오목교역],
      [YANG_양천구청역, YANG_신도림역],
      [YANG_화곡DT점, YANG_오목교역],
      [YANG_화곡DT점, YANG_등촌역],
      [YANG_오목교역, YANG_영등포구청역],
      [YANG_영등포구청역, YANG_신도림역],
      [YANG_영등포구청역, YANG_당산역],
      [YANG_영등포구청역, YANG_신길역],
      [YANG_신도림역, YANG_신길역],
      [YANG_신도림역, YANG_신풍역],
      [YANG_신풍역, YANG_신길역],
      [YANG_신길역, YANG_여의도역],
      [YANG_당산역, YANG_신도림역],
      [YANG_등촌역, YANG_당산역],
      [YANG_목동점, YANG_당산역],
      [YANG_목동점, YANG_영등포구청역],
      [YANG_목동점, YANG_오목교역],
      [YANG_목동점, YANG_화곡DT점],
      [YANG_목동점, YANG_등촌역],
      [YANG_당산역, YANG_여의도역],
      [YANG_신풍역, YANG_여의도역],
      [YANG_영등포구청역, YANG_여의도역],
      [YANG_신풍역, YANG_여의도역],
      [YANG_발산역, YANG_화곡역],
      [YANG_발산역, YANG_등촌역],
    ],
    2: [
      [YANG_화곡역, YANG_양천구청역],
      [YANG_화곡역, YANG_오목교역],
      [YANG_당산역, YANG_여의도역],
      [YANG_오목교역, YANG_당산역],
      [YANG_신월동점, YANG_화곡DT점],
      [YANG_신월동점, YANG_오목교역],
      [YANG_신월동점, YANG_양천구청역],
      [YANG_당산역, YANG_신길역],
      [YANG_까치산역, YANG_등촌역],
      [YANG_까치산역, YANG_신도림역],

      [YANG_까치산역, YANG_영등포구청역],
      [YANG_양천구청역, YANG_화곡DT점],
      [YANG_양천구청역, YANG_영등포구청역],
      [YANG_양천구청역, YANG_당산역],
      [YANG_화곡DT점, YANG_영등포구청역],
      [YANG_등촌역, YANG_오목교역],
      [YANG_오목교역, YANG_신길역],
      [YANG_발산역, YANG_까치산역],
    ],
  },
  강남: {
    1: [
      [GANGNAM_교대역, GANGNAM_강남역],
      [GANGNAM_교대역, GANGNAM_양재],
      [GANGNAM_교대역, GANGNAM_도곡동점],
      [GANGNAM_교대역, GANGNAM_선릉역],
      [GANGNAM_강남역, GANGNAM_논현역],
      [GANGNAM_강남역, GANGNAM_신논현역],
      [GANGNAM_강남역, GANGNAM_선릉역],
      [GANGNAM_강남역, GANGNAM_양재],
      [GANGNAM_강남역, GANGNAM_논현역],

      [GANGNAM_양재, GANGNAM_논현역],
      [GANGNAM_양재, GANGNAM_신논현역],
      [GANGNAM_논현역, GANGNAM_신논현역],
      [GANGNAM_논현역, GANGNAM_강남역구청역],
      [GANGNAM_양재, GANGNAM_도곡동점],
      [GANGNAM_강남역, GANGNAM_도곡동점],
      [GANGNAM_선릉역, GANGNAM_강남역구청역],
    ],
    2: [
      [GANGNAM_신논현역, GANGNAM_강남역구청역],
      [GANGNAM_양재, GANGNAM_선릉역],
      [GANGNAM_선릉역, GANGNAM_도곡동점],

      [GANGNAM_선릉역, GANGNAM_논현역],

      [GANGNAM_선릉역, GANGNAM_신논현역],
      [GANGNAM_신논현역, GANGNAM_도곡동점],

      [GANGNAM_강남역, GANGNAM_강남역구청역],
      [GANGNAM_교대역, GANGNAM_논현역],
      [GANGNAM_교대역, GANGNAM_신논현역],
    ],
  },
  동대문: {
    1: [
      [DONG_혜화역, DONG_동대문역],
      [DONG_혜화역, DONG_성신여대점],
      [DONG_혜화역, DONG_신설동역],
      [DONG_혜화역, DONG_길음역],
      [DONG_동대문역, DONG_왕십리역],
      [DONG_동대문역, DONG_성신여대점],
      [DONG_동대문역, DONG_신설동역],
      [DONG_동대문역, DONG_안암역],

      [DONG_성신여대점, DONG_길음역],
      [DONG_성신여대점, DONG_월곡역],
      [DONG_성신여대점, DONG_안암역],
      [DONG_길음역, DONG_월곡역],
      [DONG_길음역, DONG_석계역],
      [DONG_길음역, DONG_안암역],
      [DONG_월곡역, DONG_석계역],
      [DONG_월곡역, DONG_경희대점],
      [DONG_월곡역, DONG_서울시립대점],
      [DONG_신설동역, DONG_안암역],
      [DONG_신설동역, DONG_왕십리역],
      [DONG_신설동역, DONG_서울시립대점],
      [DONG_신설동역, DONG_경희대점],
      [DONG_신설동역, DONG_딥십리역],
      [DONG_안암역, DONG_서울시립대점],
      [DONG_안암역, DONG_경희대점],
      [DONG_안암역, DONG_월곡역],
      [DONG_안암역, DONG_석계역],
      [DONG_왕십리역, DONG_딥십리역],
      [DONG_왕십리역, DONG_서울시립대점],
      [DONG_왕십리역, DONG_경희대점],
      [DONG_경희대점, DONG_서울시립대점],
      [DONG_서울시립대점, DONG_딥십리역],
      [DONG_서울시립대점, DONG_장안동사거리점],
      [DONG_서울시립대점, DONG_석계역],
      [DONG_딥십리역, DONG_장안동사거리점],
      [DONG_화랑대역, DONG_월곡역],
      [DONG_화랑대역, DONG_석계역],
    ],
    2: [
      [DONG_혜화역, DONG_안암역],
      [DONG_혜화역, DONG_왕십리역],
      [DONG_동대문역, DONG_월곡역],

      [DONG_동대문역, DONG_딥십리역],
      [DONG_동대문역, DONG_서울시립대점],
      [DONG_성신여대점, DONG_석계역],
      [DONG_성신여대점, DONG_딥십리역],
      [DONG_성신여대점, DONG_왕십리역],
      [DONG_길음역, DONG_경희대점],
      [DONG_길음역, DONG_서울시립대점],
      [DONG_신설동역, DONG_장안동사거리점],
      [DONG_신설동역, DONG_길음역],
      [DONG_신설동역, DONG_월곡역],
      [DONG_신설동역, DONG_석계역],
      [DONG_안암역, DONG_왕십리역],
      [DONG_안암역, DONG_딥십리역],
      [DONG_왕십리역, DONG_장안동사거리점],
      [DONG_경희대점, DONG_석계역],
      [DONG_경희대점, DONG_장안동사거리점],
      [DONG_경희대점, DONG_장안동사거리점],
      [DONG_경희대점, DONG_딥십리역],
    ],
  },
  인천: { 1: [[INC_송도점, INC_송도점DT점]], 2: [[INC_인하대점, INC_구월동점]] },
};
