import { STUDY_MAIN_IMAGES } from "../../../assets/images/studyMain";
import { StudyPlaceProps } from "../../../types/models/studyTypes/study-entity.types";

/**
 * 카공족 실제 데이터 연동 전, UI 디자인 확인용 임시 데이터.
 * 실제 데이터가 연결되면 이 파일과 StudyPageMap.tsx의 병합 코드(placeData useMemo)만 지우면 된다.
 */
export const MOCK_KAGONGJOK_PLACES: StudyPlaceProps[] = [
  {
    _id: "kagongjok-demo-gangnam",
    location: {
      name: "카공족 강남점",
      address: "서울특별시 강남구 테헤란로 123",
      latitude: 37.498,
      longitude: 127.027,
    },
    image: STUDY_MAIN_IMAGES[0],
    operatingHours: [["매일", "00:00 - 24:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: true,
      hasGoodWifi: true,
      hasGroupSeats: true,
      hasParking: false,
      hasComfortableSeats: true,
      hasCleanRestroom: true,
      hasGoodValueDrinks: false,
      hasTimeLimit: false,
    },
  },
  {
    _id: "kagongjok-demo-sinchon",
    location: {
      name: "카공족 신촌점",
      address: "서울특별시 서대문구 신촌로 45",
      latitude: 37.5559,
      longitude: 126.9368,
    },
    image: STUDY_MAIN_IMAGES[1],
    operatingHours: [["매일", "09:00 - 22:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: false,
      hasGoodWifi: true,
      hasGroupSeats: false,
      hasParking: false,
      hasComfortableSeats: true,
      hasCleanRestroom: true,
      hasGoodValueDrinks: false,
      hasTimeLimit: true,
    },
  },
  {
    _id: "kagongjok-demo-sinchon",
    location: {
      name: "카공족 신촌점",
      address: "서울특별시 서대문구 신촌로 45",
      latitude: 37.5559,
      longitude: 126.9968,
    },
    image: STUDY_MAIN_IMAGES[1],
    operatingHours: [["매일", "09:00 - 22:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: false,
      hasGoodWifi: true,
      hasGroupSeats: false,
      hasParking: false,
      hasComfortableSeats: true,
      hasCleanRestroom: true,
      hasGoodValueDrinks: false,
      hasTimeLimit: true,
    },
  },
  {
    _id: "kagongjok-demo-kondae",
    location: {
      name: "카공족 건대점",
      address: "서울특별시 광진구 아차산로 29",
      latitude: 37.5405,
      longitude: 127.0693,
    },
    image: STUDY_MAIN_IMAGES[2],
    operatingHours: [["매일", "08:00 - 23:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: false,
      hasGoodWifi: true,
      hasGroupSeats: true,
      hasParking: true,
      hasComfortableSeats: true,
      hasCleanRestroom: false,
      hasGoodValueDrinks: false,
      hasTimeLimit: false,
    },
  },
  {
    _id: "kagongjok-demo-kondae",
    location: {
      name: "카공족 건대점",
      address: "서울특별시 광진구 아차산로 29",
      latitude: 37.5805,
      longitude: 127.0693,
    },
    image: STUDY_MAIN_IMAGES[2],
    operatingHours: [["매일", "08:00 - 23:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: false,
      hasGoodWifi: true,
      hasGroupSeats: true,
      hasParking: true,
      hasComfortableSeats: true,
      hasCleanRestroom: false,
      hasGoodValueDrinks: false,
      hasTimeLimit: false,
    },
  },
  {
    _id: "kagongjok-demo-kondae",
    location: {
      name: "카공족 건대점",
      address: "서울특별시 광진구 아차산로 29",
      latitude: 37.5605,
      longitude: 127.0593,
    },
    image: STUDY_MAIN_IMAGES[2],
    operatingHours: [["매일", "08:00 - 23:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: false,
      hasGoodWifi: true,
      hasGroupSeats: true,
      hasParking: true,
      hasComfortableSeats: true,
      hasCleanRestroom: false,
      hasGoodValueDrinks: false,
      hasTimeLimit: false,
    },
  },
  {
    _id: "kagongjok-demo-kondae",
    location: {
      name: "카공족 건대점",
      address: "서울특별시 광진구 아차산로 29",
      latitude: 37.7605,
      longitude: 127.0093,
    },
    image: STUDY_MAIN_IMAGES[2],
    operatingHours: [["매일", "08:00 - 23:00"]],
    spaceType: "study_space",
    brand: "kagongjok",
    studyCafeMeta: {
      is24Hours: false,
      hasGoodWifi: true,
      hasGroupSeats: true,
      hasParking: true,
      hasComfortableSeats: true,
      hasCleanRestroom: false,
      hasGoodValueDrinks: false,
      hasTimeLimit: false,
    },
  },
];
